/* DTS,INC.
 * 5220 LAS VIRGENES ROAD
 * CALABASAS, CA 91302  USA
 *
 * ©DTS, INC.  ALL RIGHTS RESERVED.
 *
 * THIS SOFTWARE, ANY COMPONENTS THEREOF, AND ANY RELATED DOCUMENTATION (THE “PRODUCT”)
 * CONTAINS CONFIDENTIAL PROPRIETARY INFORMATION OWNED BY DTS, INC. AND/OR ITS
 * AFFILIATES (“DTS”) INCLUDING BUT NOT LIMITED TO TRADE SECRETS, KNOW-HOW,
 * TECHNICAL, AND BUSINESS INFORMATION.  UNLESS OTHERWISE PROVIDED UNDER THE
 * TERMS OF A FULLY-EXECUTED WRITTEN AGREEMENT BY AND BETWEEN THE RECIPIENT
 * HEREOF AND DTS, ALL USE, DUPLICATION, DISCLOSURE, OR DISTRIBUTION OF THE
 * PRODUCT, IN ANY FORM, IS PROHIBITED AND IS A VIOLATION OF STATE, FEDERAL, AND
 * INTERNATIONAL LAWS. THE PRODUCT CONTAINS CONFIDENTIAL, PROPRIETARY TRADE SECRETS,
 * AND IS PROTECTED BY APPLICABLE COPYRIGHT LAW AND/OR PATENT LAW. BOTH CIVIL AND
 * CRIMINAL PENALTIES APPLY.
 *
 * ALGORITHMS, DATA STRUCTURES AND METHODS CONTAINED IN THE PRODUCT MAY BE
 * PROTECTED BY ONE OR MORE PATENTS OR PATENT APPLICATIONS. UNLESS OTHERWISE
 * PROVIDED UNDER THE TERMS OF A FULLY-EXECUTED WRITTEN AGREEMENT BY AND BETWEEN
 * THE RECIPIENT HEREOF AND DTS, THE FOLLOWING TERMS SHALL APPLY TO ANY USE OF
 * THE PRODUCT:  (I) USE OF THE PRODUCT IS AT THE RECIPIENT'S SOLE RISK; (II) THE
 * PRODUCT IS PROVIDED "AS IS" AND WITHOUT WARRANTY OF ANY KIND AND DTS EXPRESSLY
 * DISCLAIMS ALL WARRANTIES, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO
 * ANY IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE,
 * REGARDLESS OF WHETHER DTS KNOWS OR HAS REASON TO KNOW OF THE USER'S PARTICULAR
 * NEEDS; (III) DTS DOES NOT WARRANT THAT THE PRODUCT MEET USER'S REQUIREMENTS,
 * OR THAT ANY ALLEGED DEFECTS IN THE PRODUCT WILL BE CORRECTED; (IV) DTS DOES
 * NOT WARRANT THAT THE OPERATION OF ANY HARDWARE OR SOFTWARE ASSOCIATED WITH THE
 * PRODUCT WILL BE UNINTERRUPTED OR ERROR-FREE; AND (V) UNDER NO CIRCUMSTANCES,
 * INCLUDING NEGLIGENCE, SHALL DTS OR THE DIRECTORS, OFFICERS, EMPLOYEES, OR
 * AGENTS OF DTS, BE LIABLE TO USER FOR ANY INCIDENTAL, INDIRECT, SPECIAL, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING BUT NOT LIMITED TO DAMAGES FOR LOSS OF BUSINESS
 * PROFITS, BUSINESS INTERRUPTION, AND LOSS OF BUSINESS INFORMATION) ARISING OUT
 * OF THE USE, MISUSE, OR INABILITY TO USE THE PRODUCT.
 */

package com.dts.dtsaudioprocessing.listener;

/**
 * Listener to be executed when user confirms a dialog
 */
public interface DialogListener {
    void onDialogConfirm();
}
